name: intask
description: Prototype 1

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_text_kit: ^1.3.0
  loading_animation_widget: ^1.2.0+1
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  cloud_firestore: ^3.1.17
  google_sign_in: ^5.3.2
  font_awesome_flutter: ^10.1.0
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.0+1

flutter_native_splash:
  color: "#012afe"
  image: assets/images/splash.png

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: SFUIDisplay
      fonts:
        - asset: assets/fonts/SFUIDisplay-Bold.ttf
        - asset: assets/fonts/SFUIDisplay-Regular.otf
        - asset: assets/fonts/SFUIDisplay-Heavy.otf